apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f4dlq36k3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/f4dlq36k3-java-quarkus-gitops